# EXAMPLE .tf47Tools.cfg FILE
# Please see the comments for each option. Most options can be left
# off for sane defaults.

Info:
  # Project name
  # This is used for naming the release files.
  # Default: Current folder name
  project: Domination
  #Default Island
  #This is used to append the default Island to the PBO
  defaultIsland: altis
GitHub:
  org: TaskForce47
  repo: BMR_Insurgency.Altis
