#include "TF47Modules\TF47ServicePoint\TF47ServicePointMacros.hpp"

// Marker wo der SP sein soll
tf47_modules_sp_markers = ["marker_sp_ground_1","marker_sp_ground_2","marker_sp_air","marker_sp_air_1","marker_sp_air_2"];

if(worldName == "Takistan") then {
    tf47_modules_sp_markers = ["marker_sp_ground","marker_sp_ground_1","marker_sp_ground_2","marker_sp_ground_3","marker_sp_air","marker_sp_air_1","marker_sp_air_2"];
};
if(worldName == "Zargabad") then {
    tf47_modules_sp_markers = ["marker_sp_ground_1","marker_sp_ground_2","marker_sp_air"];
};

SERVICEPOINT_LOADOUT_CONFIG_BEGIN
// Ein Loadout
// Name
// Module true/false (Ist es ein Modul wird das Inventrar nicht geleert)
// Item Classname, Anzahl

SERVICEPOINT_LOADOUT_NAME("Basic Loadout")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_m4a1_carryhandle",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_mag_30Rnd_556x45_Mk318_Stanag",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhsusf_100Rnd_556x45_soft_pouch",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_M136",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_elasticBandage",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_packingBandage",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EarPlugs",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("Binocular",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACRE_PRC152",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EntrenchingTool",1)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Anti-Tank Loadout")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_smaw_green",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_m4a1_carryhandle",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_mag_30Rnd_556x45_Mk318_Stanag",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_mag_smaw_HEAA",6)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_mag_smaw_HEDP",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_optic_smaw",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EarPlugs",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("Binocular",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACRE_PRC152",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EntrenchingTool",1)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Infanterie Support Loadout")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_fgm148",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_m4a1_carryhandle",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_mag_30Rnd_556x45_Mk318_Stanag",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhsusf_100Rnd_556x45_soft_pouch",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhsusf_100Rnd_762x51_m80a1epr",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_M136",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_elasticBandage",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_packingBandage",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EarPlugs",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("Binocular",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACRE_PRC152",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EntrenchingTool",1)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Medic Loadout")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_m4a1_carryhandle",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_mag_30Rnd_556x45_Mk318_Stanag",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_elasticBandage",50)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_packingBandage",50)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_fieldDressing",50)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_bloodIV_500",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_bloodIV_250",15)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_epinephrine",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_morphine",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_personalAidKit",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_surgicalKit",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_bodyBag",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_salineIV_250",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EntrenchingTool",2)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Anti-Tank Loadout")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_fgm148",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_m4a1_carryhandle",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_mag_30Rnd_556x45_Mk318_Stanag",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhsusf_100Rnd_556x45_soft_pouch",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_fgm148_magazine_AT",6)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_M136",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EarPlugs",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("Binocular",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACRE_PRC152",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EntrenchingTool",1)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Medic Module")
SERVICEPOINT_LOADOUT_IS_MODULE(TRUE)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_elasticBandage",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_packingBandage",20)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_surgicalKit",10)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_salineIV_250",10)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Basic Marine Loadout")
SERVICEPOINT_LOADOUT_IS_MODULE(FALSE)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_M136_hedp",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_M136",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_m16a4_carryhandle",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_weap_m249_pip",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_30Rnd_556x45_Stanag_Mk318_mag",25)
SERVICEPOINT_LOADOUT_ADD_ITEM("rhs_200rnd_556x45_M_SAW",5)
SERVICEPOINT_LOADOUT_ADD_ITEM("DemoCharge_Remote_Mag",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_M26_Clacker",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("HandGrenade",6)
SERVICEPOINT_LOADOUT_ADD_ITEM("SmokeShell",8)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EarPlugs",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EntrenchingTool",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("ItemGPS",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Clacker",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("ToolKit",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACRE_PRC152",4)

SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Additional Equipment Modul")
SERVICEPOINT_LOADOUT_IS_MODULE(True)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EarPlugs",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_EntrenchingTool",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ItemGPS",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Clacker",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACRE_PRC152",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("DemoCharge_Remote_Mag",4)
SERVICEPOINT_LOADOUT_ADD_ITEM("HandGrenade",6)
SERVICEPOINT_LOADOUT_ADD_ITEM("SmokeShell",8)
SERVICEPOINT_LOADOUT_ADD_ITEM("ToolKit",1)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Flashlight_XL50",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_MapTools",2)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Vector",2)

SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_CONFIG_END

// ACE Loadouts analog wie bei Vanilla
SERVICEPOINT_ACE_LOADOUT_CONFIG_BEGIN
SERVICEPOINT_LOADOUT_NAME("Wheels")
SERVICEPOINT_LOADOUT_IS_MODULE(TRUE)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Wheel",1)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_LOADOUT_NAME("Tracks")
SERVICEPOINT_LOADOUT_IS_MODULE(TRUE)
SERVICEPOINT_LOADOUT_ADD_ITEM("ACE_Track",1)
SERVICEPOINT_LOADOUT_END

SERVICEPOINT_ACE_LOADOUT_CONFIG_END
