#include "TF47CoreScripts\configMacros.hpp"

// nicht anfassen
WHITELIST(ON)
WHITELIST_SYSTEM(0)

// mögliche whitelists sind AIR, TANK, CCT
// ein fahrzeug zu einer whitelist (AIR) hinzufügen erlaubte slots
//[fahrzeug, AIR, ["SLOTNAME", "SLOTNAME2"]] call tf47_core_whitelist_fnc_registerWhitelist;

// ein slot (SLOTNAME) mit einer Whitelist (CCT) Beschränkung versehen
REGISTER_SLOT_BEGIN

REGISTER_SLOT("T1_ARM", TANK)
REGISTER_SLOT("T2_ARM", TANK)
REGISTER_SLOT("T3_ARM", TANK)
REGISTER_SLOT("T4_ARM", TANK)
REGISTER_SLOT("T5_ARM", TANK)
REGISTER_SLOT("T6_ARM", TANK)
REGISTER_SLOT("T7_ARM", TANK)
REGISTER_SLOT("T8_ARM", TANK)

REGISTER_SLOT("H1_HELO", AIR)
REGISTER_SLOT("H2_HELO", AIR)
REGISTER_SLOT("H3_HELO", AIR)
REGISTER_SLOT("H4_HELO", AIR)
REGISTER_SLOT("H5_HELO", AIR)
REGISTER_SLOT("H6_HELO", AIR)
REGISTER_SLOT("H7_HELO", AIR)
REGISTER_SLOT("H8_HELO", AIR)
REGISTER_SLOT("H1_HELOA", AIR)
REGISTER_SLOT("H2_HELOA", AIR)
REGISTER_SLOT("H3_HELOA", AIR)
REGISTER_SLOT("H4_HELOA", AIR)

REGISTER_SLOT("F1_PLNA", AIR)
REGISTER_SLOT("F2_PLNA", AIR)
REGISTER_SLOT_END

// Nicht anfassen
TICKETSYSTEM(ON)
TICKETSYSTEM_MISSIONID(11)

TICKETSYSTEM_MISSIONAME(blub)

// Update Zeit eines Fahrzeug Markers in s
TICKETSYSTEM_MARKER_TRACKING_DELAY(5)

// Anzahl Tickets Start
TICKETSYSTEM_TICKETS_START(100)

// Softcap
TICKETSYSTEM_SOFTCAP(100)

// Hardcap
TICKETSYSTEM_HARDCAP(150)

// Nicht anfanssen
TICKETSYSTEM_TRACKING(ON)

// Marker Farbe Standard
TICKETSYSTEM_TRACKING_DEFAULT("ColorWEST")

// Marker Farbe Angriff
TICKETSYSTEM_TRACKING_ATTACK("ColorOrange")

// Marker Farbe Transport
TICKETSYSTEM_TRACKING_TRANSPORT("ColorGreen")

// Nicht anfassen
TICKETSYSTEM_DETECTION_MODE(0)

// Standard Ticketkosten für einen Spieler
REGISTER_DEFAULT(2)

// Ticketkosten für einen bestimmten Slot
REGISTER_SLOT_TICKETCOST_BEGIN
REGISTER_TICKETCOST("C1_INF", 15)
REGISTER_TICKETCOST("C2_INF", 10)
REGISTER_TICKETCOST("C3_INF", 4)

REGISTER_TICKETCOST("S1_Inf", 5)
REGISTER_TICKETCOST("S2_INF", 3)
REGISTER_TICKETCOST("S3_INF", 4)
REGISTER_TICKETCOST("S8_INF", 3)
REGISTER_TICKETCOST("S9_INF", 4)

REGISTER_TICKETCOST("S14_INF", 5)
REGISTER_TICKETCOST("S15_INF", 3)
REGISTER_TICKETCOST("S16_INF", 4)
REGISTER_TICKETCOST("S21_INF", 3)
REGISTER_TICKETCOST("S22_INF", 4)

REGISTER_TICKETCOST("S27_INF", 5)
REGISTER_TICKETCOST("S28_INF", 3)
REGISTER_TICKETCOST("S29_INF", 4)
REGISTER_TICKETCOST("S34_INF", 3)
REGISTER_TICKETCOST("S35_INF", 4)

REGISTER_TICKETCOST("T1_ARM", 8)
REGISTER_TICKETCOST("T2_ARM", 5)
REGISTER_TICKETCOST("T3_ARM", 5)
REGISTER_TICKETCOST("T4_ARM", 5)

REGISTER_TICKETCOST("T5_ARM", 8)
REGISTER_TICKETCOST("T6_ARM", 5)
REGISTER_TICKETCOST("T7_ARM", 5)
REGISTER_TICKETCOST("T8_ARM", 5)

REGISTER_TICKETCOST("H1_HELO", 10)
REGISTER_TICKETCOST("H2_HELO", 5)
REGISTER_TICKETCOST("H3_HELO", 5)
REGISTER_TICKETCOST("H4_HELO", 5)
REGISTER_TICKETCOST("H5_HELO", 10)
REGISTER_TICKETCOST("H6_HELO", 5)
REGISTER_TICKETCOST("H7_HELO", 5)
REGISTER_TICKETCOST("H8_HELO", 5)

REGISTER_TICKETCOST("H1_HELOA", 10)
REGISTER_TICKETCOST("H2_HELOA", 10)
REGISTER_TICKETCOST("H3_HELOA", 10)
REGISTER_TICKETCOST("H4_HELOA", 10)

REGISTER_TICKETCOST("F_PLNA", 15)
REGISTER_TICKETCOST("F_PLNA", 15)

REGISTER_SLOT_TICKETCOST_END

//Vehicle Desertion
TICKETSYSTEM_DESERTION_TIME(7200)
TICKETSYSTEM_DESERTION_MARKER("flagge")