#include "TF47Modules\TF47VehicleSpawner\TF47VehicleSpawnerMacros.hpp"

VS_CONFIG_BEGIN
["GroundVehicles",
  [
    [
      "rhsusf_mrzr4_d",
      "B_Quadbike_01_F"
    ],
    0, 1, []
  ],
  [
    [
      "BWA3_Eagle_Fleck",
      "rhsusf_m998_w_2dr",
      "rhsusf_m998_w_s_2dr",
      "rhsusf_m998_w_2dr_halftop",
      "rhsusf_m998_w_s_2dr_halftop",
      "rhsusf_m998_w_2dr_fulltop",
      "rhsusf_m998_w_s_2dr_fulltop",
      "rhsusf_m998_w_4dr",
      "rhsusf_m998_w_s_4dr",
      "rhsusf_m998_w_4dr_halftop",
      "rhsusf_m998_w_s_4dr_halftop",
      "rhsusf_m998_w_4dr_fulltop",
      "rhsusf_m998_w_s_4dr_fulltop",
      "rhsusf_m1025_w",
      "rhsusf_m1025_w_s",
      "UK3CB_BAF_LandRover_Hard_FFR_Green_A_MTP",
      "UK3CB_BAF_LandRover_Snatch_FFR_Green_A_MTP",
      "UK3CB_BAF_LandRover_Soft_FFR_Green_A_MTP"
    ],
    0, 5, []
  ],
  [
    [
      "BWA3_Eagle_FLW100_Fleck",
      "rhsusf_m1025_w_m2",
      "rhsusf_m1025_w_s_m2",
      "rhsusf_m1025_w_mk19",
      "rhsusf_m1025_w_s_Mk19",
      "UK3CB_BAF_Jackal2_GMG_W_MTP",
      "UK3CB_BAF_Jackal2_L2A1_W_MTP",
      "UK3CB_BAF_Coyote_Passenger_L134A1_W_MTP",
      "UK3CB_BAF_Coyote_Passenger_L111A1_W_MTP",
      "UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A_MTP",
      "UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A_MTP",
      "UK3CB_BAF_LandRover_WMIK_HMG_FFR_Green_A_MTP",
      "UK3CB_BAF_LandRover_WMIK_Milan_FFR_Green_A_MTP"
    ],
    0, 10, []
  ],
  [
    [
      "rhsusf_M1117_W",
      "rhsusf_m113_usarmy",
      "rhsusf_m113_usarmy_unarmed",
      "rhsusf_m113_usarmy_M240",
      "rhsusf_m113_usarmy_MK19",
      "rhsusf_rg33_usmc_wd",
      "rhsusf_rg33_m2_usmc_wd",
      "rhsusf_M1220_usarmy_wd",
      "rhsusf_M1220_M153_M2_usarmy_wd",
      "rhsusf_M1220_M2_usarmy_wd",
      "rhsusf_M1220_MK19_usarmy_wd",
      "rhsusf_M1230_M2_usarmy_wd",
      "rhsusf_M1230_MK19_usarmy_wd",
      "rhsusf_M1232_usarmy_wd",
      "rhsusf_M1232_M2_usarmy_wd",
      "rhsusf_M1232_MK19_usarmy_wd",
      "rhsusf_M1237_M2_usarmy_wd",
      "rhsusf_M1237_MK19_usarmy_wd",
      "Redd_Tank_Fuchs_1A4_Jg_Flecktarn",
      "Redd_Tank_Fuchs_1A4_Jg_Milan_Flecktarn",
      "Redd_Tank_Fuchs_1A4_Pi_Flecktarn",
      "Redd_Tank_Fuchs_1A4_San_Flecktarn"
    ],
    0, 15, []
  ],
  [
    [
      "rhsusf_M1230a1_usarmy_wd"
    ],
    0, 25, []
  ],
	[
    [
      "rhsusf_M1085A1P2_B_WD_Medical_fmtv_usarmy"
    ],
    0, 30, []
  ],
	[
    [
      "rhsusf_M978A4_BKIT_usarmy_wd",
      "rhsusf_M977A4_AMMO_BKIT_M2_usarmy_wd",
      "rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd",
			"UK3CB_BAF_Coyote_Logistics_L134A1_W_MTP",
      "UK3CB_BAF_Coyote_Logistics_L111A1_W_MTP"
    ],
    0, 25, []
  ],
	[
    [
      "rhsusf_M1078A1R_SOV_M2_D_fmtv_socom",
      "rhsusf_M1078A1P2_WD_fmtv_usarmy",
      "rhsusf_M1078A1P2_B_WD_fmtv_usarmy",
      "rhsusf_M1078A1P2_B_M2_WD_fmtv_usarmy",
      "rhsusf_M1083A1P2_WD_fmtv_usarmy",
      "rhsusf_M1083A1P2_B_WD_fmtv_usarmy",
      "rhsusf_M1083A1P2_B_M2_WD_fmtv_usarmy",
      "rhsusf_M1078A1P2_WD_flatbed_fmtv_usarmy",
      "rhsusf_M1078A1P2_B_WD_flatbed_fmtv_usarmy",
      "rhsusf_M1078A1P2_B_M2_WD_flatbed_fmtv_usarmy",
      "rhsusf_M1083A1P2_WD_flatbed_fmtv_usarmy",
      "rhsusf_M1083A1P2_B_WD_flatbed_fmtv_usarmy",
      "rhsusf_M1083A1P2_B_M2_WD_flatbed_fmtv_usarmy",
      "rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy",
      "rhsusf_M1084A1P2_WD_fmtv_usarmy",
      "rhsusf_M1084A1P2_B_WD_fmtv_usarmy",
      "UK3CB_BAF_LandRover_Amb_FFR_Green_A_MTP",
      "rhsusf_M1084A1P2_B_M2_WD_fmtv_usarmy",
      "rhsusf_M1084A1R_SOV_M2_D_fmtv_socom"
    ],
    0, 15, []
  ],
  [
    [
      "Redd_Marder_1A5_Flecktarn",
      "Redd_Tank_Wiesel_1A2_TOW_Flecktarn",
      "Redd_Tank_Wiesel_1A4_MK20_Flecktarn",
      "BWA3_Puma_Fleck",
			"RHS_M2A2_wd",
      "RHS_M2A2_BUSKI_WD",
      "RHS_M2A3_BUSKI_wd",
      "RHS_M2A3_wd",
      "RHS_M6_wd"
			"UK3CB_BAF_FV432_Mk3_GPMG_Green",
      "UK3CB_BAF_FV432_Mk3_RWS_Green"
    ],
    2, 25,
    [
      "T1_ARM",
      "T2_ARM",
      "T3_ARM",
      "T4_ARM",
      "T5_ARM",
      "T6_ARM",
      "T7_ARM",
      "T8_ARM"
    ]
  ],
  [
    [
      "BWA3_Leopard2A6M_Fleck",
      "rhsusf_m1a1aimwd_usarmy",
      "rhsusf_m1a1aim_tuski_wd",
      "rhsusf_m1a1fep_wd",
      "rhsusf_m1a1fep_od",
      "rhsusf_m1a1hc_wd",
      "rhsusf_m1a2sep1wd_usarmy",
      "rhsusf_m1a2sep1tuskiwd_usarmy",
      "rhsusf_m1a2sep1tuskiiwd_usarmy"
    ],
    2, 30,
    [
      "T1_ARM",
      "T2_ARM",
      "T3_ARM",
      "T4_ARM",
      "T5_ARM",
      "T6_ARM",
      "T7_ARM",
      "T8_ARM"
    ]
  ],
  [
    [
      "rhsusf_m109_usarmy",
      "RHS_M119_WD"
    ],
    2, 15,
    [
      "T1_ARM",
      "T2_ARM",
      "T3_ARM",
      "T4_ARM",
      "T5_ARM",
      "T6_ARM",
      "T7_ARM",
      "T8_ARM"
    ]
  ],
  [
    [
      "B_Slingload_01_Cargo_F",
      "B_Slingload_01_Medevac_F",
      "B_Slingload_01_Ammo_F",
      "B_Slingload_01_Repair_F",
      "B_Slingload_01_Fuel_F"
    ],
    0, 10, []
  ],
  [
    [
      "ACE_Box_82mm_Mo_Combo",
      "ACE_Box_82mm_Mo_HE",
      "ACE_Box_82mm_Mo_Illum",
      "ACE_Box_82mm_Mo_Smoke",
      "ACE_Box_Chemlights",
      "ACE_medicalSupplyCrate_advanced",
      "ACE_medicalSupplyCrate",
      "B_supplyCrate_F",
      "Box_NATO_Support_F",
      "ACE_Wheel",
      "ACE_Track",
      "Land_CanisterFuel_F"
    ],
    0, -1, []
  ]
],
["AirVehicles",
  [
    [
      "RHS_MELB_H6M",
      "RHS_MELB_MH6M"
    ],
    1, 15,
    [
      "H1_HELO",
      "H2_HELO",
      "H3_HELO",
      "H4_HELO",
      "H5_HELO",
      "H6_HELO",
      "H7_HELO",
      "H8_HELO"
    ]
  ],
  [
    [
      "RHS_UH60M",
      "RHS_UH60M2",
      "RHS_UH60M_ESSS",
      "RHS_UH60M_ESSS2",
      "RHS_UH1Y_FFAR",
      "RHS_UH1Y",
      "RHS_UH1Y_UNARMED",
    	"UK3CB_BAF_Wildcat_AH1_TRN_8A_MTP",
      "UK3CB_BAF_Wildcat_AH1_HEL_8A_MTP",
      "UK3CB_BAF_Wildcat_AH1_CAS_8D_MTP",
	     "UK3CB_BAF_Wildcat_AH1_CAS_8C_MTP",
      "UK3CB_BAF_Wildcat_AH1_CAS_8B_MTP",
      "UK3CB_BAF_Wildcat_AH1_CAS_8A_MTP"
    ],
    1, 20,
    [
      "H1_HELO",
      "H2_HELO",
      "H3_HELO",
      "H4_HELO",
      "H5_HELO",
      "H6_HELO",
      "H7_HELO",
      "H8_HELO"
    ]
  ],
	[
    [
      "RHS_UH60M_MEV",
      "RHS_UH60M_MEV2",
      "UK3CB_BAF_Merlin_HC3_CSAR_MTP"
    ],
    1, 30,
    [
      "H1_HELO",
      "H2_HELO",
      "H3_HELO",
      "H4_HELO",
      "H5_HELO",
      "H6_HELO",
      "H7_HELO",
      "H8_HELO"
    ]
  ],
	[
    [
      "rhsusf_CH53E_USMC",
      "RHS_CH_47F",
      "UK3CB_BAF_Merlin_HC3_18_GPMG_MTP",
			"UK3CB_BAF_Merlin_HC3_Cargo_MTP"
    ],
    1, 25,
    [
      "H1_HELO",
      "H2_HELO",
      "H3_HELO",
      "H4_HELO",
      "H5_HELO",
      "H6_HELO",
      "H7_HELO",
      "H8_HELO"
    ]
  ],
  [
    [
      "RHS_MELB_AH6M"
    ],
    1, 20,
    [
      "H1_HELOA",
      "H2_HELOA",
      "H3_HELOA",
      "H4_HELOA"
    ]
  ],
  [
    [
      "BWA3_Tiger_Gunpod_FZ",
      "BWA3_Tiger_Gunpod_PARS",
      "BWA3_Tiger_Gunpod_Heavy",
      "RHS_AH1Z_wd"
    ],
    1, 25,
    [
      "H1_HELOA",
      "H2_HELOA",
      "H3_HELOA",
      "H4_HELOA"
    ]
  ],
  [
    [
      "BWA3_Tiger_RMK_FZ",
      "BWA3_Tiger_RMK_PARS",
      "BWA3_Tiger_RMK_Heavy",
      "BWA3_Tiger_RMK_Universal",
      "RHS_AH64D_wd",
      "RHS_AH64D_noradar_wd"
    ],
    1, 30,
    [
      "H1_HELOA",
      "H2_HELOA",
      "H3_HELOA",
      "H4_HELOA"
    ]
  ],
  [
    [
      "RHS_C130J"
    ],
    1, 20,
    [
      "F1_PLNA",
      "F2_PLNA"
    ]
  ],
  [
    [
      "rhsusf_f22",
      "RHS_A10",
      "FIR_F16C",
      "FIR_F16D"
    ],
    1, 35,
    [
      "F1_PLNA",
      "F2_PLNA"
    ]
  ],
  [
    [
      "B_Slingload_01_Cargo_F",
      "B_Slingload_01_Medevac_F",
      "B_Slingload_01_Ammo_F",
      "B_Slingload_01_Repair_F",
      "B_Slingload_01_Fuel_F"
    ],
    0, 10, []
  ],
  [
    [
      "ACE_Box_82mm_Mo_Combo",
      "ACE_Box_82mm_Mo_HE",
      "ACE_Box_82mm_Mo_Illum",
      "ACE_Box_82mm_Mo_Smoke",
      "ACE_Box_Chemlights",
      "ACE_medicalSupplyCrate_advanced",
      "ACE_medicalSupplyCrate",
      "B_supplyCrate_F",
      "Box_NATO_Support_F",
      "ACE_Wheel",
      "ACE_Track",
      "Land_CanisterFuel_F"
    ],
    0, -1, []
  ]
]
VS_CONFIG_END
